# Travis CI configuration
# Note: there are currently issues with limiting coverity to a single compiler
#       see https://github.com/travis-ci/travis-ci/issues/1975
#       Instead we use a script to decide if we should do anything

language: c
compiler:
- clang
- gcc
os:
- linux
- osx

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev # (requried for htslib+linux)
    - libbz2-dev  # (requried for htslib+linux)

before_install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi

install:
  - ./travis/install.sh
  - eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

script: ./travis/script.sh

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "T08ccfH7+agMchVPhAP/MTdVeFonkjlLvbY8nv/jQ5aZeeWP2i1Oop59MVtuaA4Vw1Ickjr1czLsHGob2OyMHwo2otEasMqacvOw38exblvjOptqN7dx2yu0qzBZdHxLd/uOad7HMfgtkVSwgpodeNR6+K+4LcCM7J6+iAWtLME="

addons:
  coverity_scan:
    project:
      name: "mcveanlab/mccortex"
      description: Build submitted via Travis CI
    notification_email: turner.isaac@gmail.com
    build_command_prepend: git submodule update --init --recursive
    build_command: make
    branch_pattern: coverity_scan
