# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc

install: cd libs && make core && cd .. && make all RELEASE=1 && make clean && make all
script: make test
