# Travis CI configuration
# Note: osx not turned on currently, but this file is set up for it.
# Note: there are currently issues with limiting coverity to a single compiler
#       see https://github.com/travis-ci/travis-ci/issues/1975
#       Instead we use a script to decide if we should do anything

language: c
compiler:
- clang
- gcc
os:
- linux
- osx

install:
  if [ `./travis/run.sh` == 'yes' ]
  then
    cd libs && make core && cd ..
  fi

script:
  if [ `./travis/run.sh` == 'yes' ]
  then
    if [ ${TRAVIS_BRANCH} == 'coverity_scan' ]
    then
      ./travis/travisci_build_coverity_scan.sh
    else
      make all RELEASE=1 && make clean && make all && make test
    fi
  fi

notifications:
  hipchat:
    rooms:
      secure: PC+3Y1rm3ddG04qdu0eMYB4KCpr9IpDyx2Uph25jdfM9CFVIZiJ2kbortMWqPvex0RChwDKNhuwh0ogO6crhTESWJ62JnFEjSrRxh+RPb+BQy1A222DexbEo4bBeiNpmQoafiNxRgot24deKAq799lbgdNUe2SpQh0yHsxd8FTE=
