# Travis CI configuration
# Note: there are currently issues with limiting coverity to a single compiler
#       see https://github.com/travis-ci/travis-ci/issues/1975
#       Instead we use a script to decide if we should do anything

language: c
compiler:
- clang
- gcc
os:
- linux
- osx

sudo: false

# Multi language support on TravisCI would be nice
# language: perl
# perl: "5.20"

before_install:
  - git submodule update --init --recursive

install:
  - ./travis/install.sh
  - eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

script: ./travis/script.sh

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "eKUTro+39sWiHx4tuvR6DbltNvXkv/qreSpzngTgT200PVLhibHgHCRbKojX8DQnAlmIZgUYt5u50W6u1V8XN3xi7gGZW/hg67VqCGgoiPp2iaWEwgWJhyK1VzJfXB59aw9NRAQyt1S1FLFbsYoPMiuC3DG4fdb6Us4j9hXjHXk="

notifications:
  # HipChat
  hipchat:
    rooms:
      secure: PC+3Y1rm3ddG04qdu0eMYB4KCpr9IpDyx2Uph25jdfM9CFVIZiJ2kbortMWqPvex0RChwDKNhuwh0ogO6crhTESWJ62JnFEjSrRxh+RPb+BQy1A222DexbEo4bBeiNpmQoafiNxRgot24deKAq799lbgdNUe2SpQh0yHsxd8FTE=
  # Gitter
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8f969771c3a52b40ec94
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
