# Travis CI configuration
# Note: osx not turned on currently, but this file is set up for it.
# Note: there are currently issues with limiting coverity to a single compiler
#       see https://github.com/travis-ci/travis-ci/issues/1975
#       Instead we use a script to decide if we should do anything

language: c
compiler:
- clang
- gcc
os:
- linux
- osx

# We require sudo to install perl JSON module
# Set to false if JSON dependency removed
sudo: required

# Multi language support on TravisCI would be nice
# language: perl
# perl: "5.20"

install:
  - sudo apt-get install libjson-pp-perl
  # - cpanm JSON # <- not available if language is not "perl"
  - ./travis/install.sh

script: ./travis/script.sh

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "eKUTro+39sWiHx4tuvR6DbltNvXkv/qreSpzngTgT200PVLhibHgHCRbKojX8DQnAlmIZgUYt5u50W6u1V8XN3xi7gGZW/hg67VqCGgoiPp2iaWEwgWJhyK1VzJfXB59aw9NRAQyt1S1FLFbsYoPMiuC3DG4fdb6Us4j9hXjHXk="

addons:
  coverity_scan:
    project:
      name: "mcveanlab/mccortex"
      description: "Build submitted via Travis CI"
    notification_email: turner.isaac@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make all"
    branch_pattern: coverity_scan

notifications:
  # HipChat
  hipchat:
    rooms:
      secure: PC+3Y1rm3ddG04qdu0eMYB4KCpr9IpDyx2Uph25jdfM9CFVIZiJ2kbortMWqPvex0RChwDKNhuwh0ogO6crhTESWJ62JnFEjSrRxh+RPb+BQy1A222DexbEo4bBeiNpmQoafiNxRgot24deKAq799lbgdNUe2SpQh0yHsxd8FTE=
  # Gitter
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8f969771c3a52b40ec94
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
