# Travis CI configuration
# Note: osx not turned on currently, but this file is set up for it.
# Note: there are currently issues with limiting coverity to a single compiler
#       see https://github.com/travis-ci/travis-ci/issues/1975
#       Instead we use a script to decide if we should do anything

language: c
compiler:
- clang
- gcc
os:
- linux
- osx

install: ./travis/install.sh

script: ./travis/script.sh

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "eKUTro+39sWiHx4tuvR6DbltNvXkv/qreSpzngTgT200PVLhibHgHCRbKojX8DQnAlmIZgUYt5u50W6u1V8XN3xi7gGZW/hg67VqCGgoiPp2iaWEwgWJhyK1VzJfXB59aw9NRAQyt1S1FLFbsYoPMiuC3DG4fdb6Us4j9hXjHXk="

notifications:
  hipchat:
    rooms:
      secure: PC+3Y1rm3ddG04qdu0eMYB4KCpr9IpDyx2Uph25jdfM9CFVIZiJ2kbortMWqPvex0RChwDKNhuwh0ogO6crhTESWJ62JnFEjSrRxh+RPb+BQy1A222DexbEo4bBeiNpmQoafiNxRgot24deKAq799lbgdNUe2SpQh0yHsxd8FTE=
