# Travis CI configuration

language: c
compiler: gcc
os: linux

sudo: false

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "GFhh3zDi4MBYXIt7eDv+7rngKfx7oDZrtCqyM7sNN+LgHNkr6ZFpec+oJ/aAnD6KEtwyPAbGkSmyHoDWC6d4F0g1Ye41Xd9KzMXlHQoAnhJo1eesdWNky3cIenPvy4Xvy4i/5l2NtroLoboz7M5frWRN+rcrN/KenApd6lpJjGk="

addons:
  coverity_scan:
    project:
      name: "mcveanlab/mccortex"
      description: "Build submitted via Travis CI"
    notification_email: turner.isaac@gmail.com
    build_command_prepend: make clean
    build_command: make all
    branch_pattern: coverity_scan

notifications:
  # HipChat
  hipchat:
    rooms:
      secure: PC+3Y1rm3ddG04qdu0eMYB4KCpr9IpDyx2Uph25jdfM9CFVIZiJ2kbortMWqPvex0RChwDKNhuwh0ogO6crhTESWJ62JnFEjSrRxh+RPb+BQy1A222DexbEo4bBeiNpmQoafiNxRgot24deKAq799lbgdNUe2SpQh0yHsxd8FTE=
  # Gitter
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8f969771c3a52b40ec94
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
